# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "create ipa"
  lane :create_ipa do

    sigh(
      force: false,
      app_identifier: "org.reactjs.native.example.graphql.native",
      adhoc: true,
    )

    increment_version_number(
      version_number: "0.0.0",
      xcodeproj: "native.xcodeproj"
    )


    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M"),
      xcodeproj: "native.xcodeproj"
    )

    build_app(
      workspace: "native.xcworkspace",
      clean: true,
      scheme: "native",
      output_name: "native.ipa",
      export_method: "ad-hoc"
    )
  end

  desc "deploy fabric"
  lane :fabric do
    crashlytics(
      crashlytics_path: "./Crashlytics.framework",
      api_token: ENV["FABRIC_API_TOKEN"],
      build_secret: ENV["FABRIC_API_SECRET"],
      ipa_path: 'native.ipa',
      notes: "fastlaneによる配布",
      notifications: true,
      groups: "develop"
    )
    
  end
end
